pipeline:
  roletest:
    image: docker.prianto.com/${IMAGE}
    pull: true
    commands:
      - pwd
      - ls -l
      - ansible --version
      - printf "[defaults]\nroles_path=../\n" > ansible.cfg
      - printf "[local]\nlocalhost ansible_connection=local\n" > tests/inventory
      - ansible-playbook tests/test.yml -i tests/inventory --syntax-check --extra-vars "rolename=${PWD##*/}"
      - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "rolename=${PWD##*/}"
      - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "rolename=${PWD##*/}" > tests/idempotence
      - cat tests/idempotence | grep -q 'changed=0.*failed=0'
  
  slack:
    image: plugins/slack
    webhook: https://slack.prianto.com/hooks/JRPTwnvvrpwwzYftb/Nck8YPFbRmiPE6ZrCDidZCAnjJw42vWbx8gKH6gCjcSM4KMz
    channel: git-prianto
    username: rocket.cat
    icon_emoji: ":drone:"

matrix:
  IMAGE:
    - debian9-ansible:latest
    - debian8-ansible:latest
    - ubuntu1604-ansible:latest